sudo: false
language: cpp
cache:
    - ccache
    - apt
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - clang-3.7
      - g++-5
      - gcc-5
